{
 "title": "BOSH: Overview",
 "description": "BOSH Overview",
 "tags": [ "bosh" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_job_healthy, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment!=\"bosh-health-check\"}, bosh_deployment)"
   },
   {
    "name": "bosh_job_name",
    "label": "Job",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name!~\"^compilation.*\"}, bosh_job_name)"
   },
   {
    "name": "bosh_job_index",
    "label": "Index",
    "query": "label_values(bosh_job_healthy{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\"}, bosh_job_index)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_healthy{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Processes Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(bosh_job_process_healthy{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_mem_percent{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Swap Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_swap_percent{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg CPU (sys)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_sys{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg CPU (user)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_user{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg CPU (wait)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_cpu_wait{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Load (avg01)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg01{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Load (avg05)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg05{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Load (avg15)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_load_avg15{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg System Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_system_disk_percent{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Ephemeral Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_ephemeral_disk_percent{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  },
  {
   "title": "Avg Persistent Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_job_persistent_disk_percent{environment=~\"$environment\",bosh_name=\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})"
    }
   ]
  }
 ]
}