{
 "title": "Prometheus: BOSH Exporter",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(bosh_last_scrape_timestamp, environment)"
   },
   {
    "name": "bosh_director",
    "label": "Director",
    "query": "label_values(bosh_last_scrape_timestamp{environment=~\"$environment\"}, bosh_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bosh_last_scrape_timestamp{environment=~\"$environment\",bosh_name=\"$bosh_director\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Scrape Status",
   "type": "singlestat",
   "description": "Whether the last scrape of metrics from BOSH resulted in an error.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(bosh_last_scrape_error{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Scrapes",
   "type": "singlestat",
   "description": "Total number of times BOSH was scraped for metrics.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_scrapes_total{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Error Scrapes",
   "type": "singlestat",
   "description": "Total number of times an error occured scraping BOSH.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(bosh_scrape_errors_total{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "description": "How long it took to scrape from BOSH.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_last_scrape_duration_seconds{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "singlestat",
   "description": "When was the last scrape from BOSH.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bosh_last_scrape_timestamp{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Deployments Scrape Duration",
   "type": "graph",
   "description": "How long it took to scrape Deployments from BOSH.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_last_deployments_scrape_duration_seconds{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Last Deployment Scrape",
   "type": "singlestat",
   "description": "When was the last Deployments scrape from BOSH.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bosh_last_deployments_scrape_timestamp{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Jobs Scrape Duration",
   "type": "graph",
   "description": "How long it took to scrape Jobs from BOSH.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_last_jobs_scrape_duration_seconds{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Last Jobs Scrape",
   "type": "singlestat",
   "description": "When was the last Jobs scrape from BOSH.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bosh_last_jobs_scrape_timestamp{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Service Discovery Scrape Duration",
   "type": "graph",
   "description": "How long it took to scrape Service Discovery from BOSH.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(bosh_last_service_discovery_scrape_duration_seconds{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Last Service Discovery Scrape",
   "type": "singlestat",
   "description": "When was the last Service Discovery scrape from BOSH.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bosh_last_service_discovery_scrape_timestamp{environment=~\"$environment\",bosh_name=\"$bosh_director\",instance=~\"$instance\"})"
    }
   ]
  }
 ]
}